### ISSUE TITLE
JWT token verification is not happening

### ISSUE THREAD

**Issue by vidhi2810** [ale-sanchez-g/villain#29]
1. Register user with "/auth/gentoken" endpoint. 
2. Create Get Request(https://supervillain.herokuapp.com/auth/verifytoken)  in postman
3. In Postman under the Authorization tab, select the Bearer Token authorization type and token’s variable value.(Received JWT token successfully over email)
4. Send the Get request
5. Here, noticed that returned response is 403 - forbidden. Even though passing all correct parameters and tokens

Please see attached image
![invalidToken](https://user-images.githubusercontent.com/20989368/155882745-33871936-ea90-4f28-8e18-ee013bfe8728.JPG)

**Comment by ale-sanchez-g** [comment]
this is not a Bearer token.

Remove Bearer from the Authorization header
