### ISSUE TITLE
Defects for COVID-19 Game from Linliya Yan

### ISSUE THREAD

**Issue by yanlin8501** [ale-sanchez-g/villain#47]
Test case 1: When add a new user with a negative score to the leaderboard via POST /v1/user, it shouldn't be accept by the system.
Step: 1. Given the authorized key, the score is -100, user name: 12345.
         2. Then execute it.
Expected result: The score shouldn't be negative.
Actual result: Adds a new user to the leaderboard successfully.

![image](https://user-images.githubusercontent.com/107088092/172752531-fff56461-8eab-4c92-8844-e053e02b13da.png)
![image](https://user-images.githubusercontent.com/107088092/172752540-b40f5f0d-9944-43d4-b19d-917f6ce570fb.png)

Test case 2: When update a user with a negative score to the leaderboard via PUT /v1/user, it shouldn't be accept in the system.
Step: 1. Given the authorized key, the score is -100, user name: string.
         2. Then execute it.
Expected result: The score shouldn't be negative.
Actual result: Update the user to the leaderboard successfully.
![image](https://user-images.githubusercontent.com/107088092/172752982-f724ce9d-4f4a-4d7a-8987-789b1a7a6acd.png)
![image](https://user-images.githubusercontent.com/107088092/172753000-9e4b3b74-4b83-4be0-9c4c-c7d44045589a.png)

Test case 3: When update a user without register to the leaderboard via PUT /v1/user, it shouldn't be accept by the system.
Step: 1. Given the new username: zzzzzz, score: 200.
         2. Then execute it.
Expected result: The new user shouldn't be updated by the system.
Actual result: The user is added to the list.
![image](https://user-images.githubusercontent.com/107088092/172753576-3a038e2a-f43e-49de-bddc-c5335211070e.png)
![image](https://user-images.githubusercontent.com/107088092/172753592-2f5261e6-d9e3-46b2-8ab4-2e4a505690a3.png)

Test case 4: When delete a existing user via DELETE /v1/user, the user should be deleted by the system.
Step: 1. Given the authorized key,  the username: string.
         2. Then execute it.
Expected result: The user should be deleted by the system.
Actual result: The system didn't get authorized.

![image](https://user-images.githubusercontent.com/107088092/172754424-912b42f6-7bed-4cb8-8157-33325eb63eaf.png)

Test case 5: When input the different password into PASSWORD and REPEAT PASSWORD boxes, then click SIGN UP button, the user shouldn't be created.
Step: 1. When input new user name: abcabc, password: 00000, repeat password: 0000
         2. When click SIGN UP button
         3. When the page shows PASSWORD DO NOT MATCH
         4. When change repeat password to 00000
         5. When click SIGN UP button again
         6. Then click REGISTER button again after click CANCEL button to shut the sign up page.
Expected result: The user should be created,  the page should shows "user create successfully", not "user already exists".
                           The register page should have no any system information after reopen it.
Actual result: The page shows that USER ALREADY EXISTS.   - image 2
                      Check /auth/user/register API with user name "abcabc" got code 400. "detail": "Key (username)=(abcabc) already exists.",  - image 3
                       The register page shows PASSWORD DO NOT MATCH  - image 4

![image](https://user-images.githubusercontent.com/107088092/172520732-d17380cf-e31f-4726-956a-9ed4b2b0a93a.png)
![image](https://user-images.githubusercontent.com/107088092/172520748-fee87d4a-2a86-4386-a125-309088dd8290.png)
![image](https://user-images.githubusercontent.com/107088092/172520710-6798f606-512c-4cfe-8492-ccf63776fb4d.png)
![image](https://user-images.githubusercontent.com/107088092/172522117-25354726-9533-4d3d-81e8-9e9cda94d5a8.png)

Test case 6: When login with a user name with special characters, the page should run normally.
Step: 1. When input user name with special characters and password. User name: abc123!@#, password:000000
         2. Then login to the game page
Expected result: The game should run normally.
Actual result: The game page doesn't load properly.

![image](https://user-images.githubusercontent.com/107088092/172744261-99499685-ccad-4b12-bad1-db157ce8f24a.png)

Test case 7: When relogin with a user name with no special characters after game is over every time, the game pages should load properly.
Step: 1. When input user name with no special characters and password. User name: aaaaa, password: 00000
         2. Then start to play the game.
Expected result: The game page should load properly.
Actual result: The first two pages are the same. 
                      The pictures in the 3rd, 7th, 10th page doesn't load.
                      The pictures in the 8th and 9th page are the same.

page 1&2
![image](https://user-images.githubusercontent.com/107088092/172746906-3257244d-41a9-4f7a-98bc-e060e8d0fbcf.png)
page 3
![image](https://user-images.githubusercontent.com/107088092/172746661-d9832784-2313-41bb-b31c-f7dc428ea801.png)
page 7
![image](https://user-images.githubusercontent.com/107088092/172746961-a70f3206-76dd-4b16-a3b0-bd86fa112356.png)
page 8&9
![image](https://user-images.githubusercontent.com/107088092/172747456-81c943fe-cec5-41f9-8b78-08be1a7bcbca.png)
![image](https://user-images.githubusercontent.com/107088092/172747040-c9b21e2f-01bf-451d-b38a-c9ddcc077999.png)
page 10
![image](https://user-images.githubusercontent.com/107088092/172747097-0965e952-201f-4000-ac60-aa39d6f8292b.png)

Test case 8: When answer the 13th question, the game should continue.
Step: 1. Given user name with no special characters and password. User name: aaaaa, password: 00000
         2. When start to play the game and play till the 13th story chapter.
         3. Then click CONTINUE button.
Expected result: The game should continue.
Actual result: The game jump out to the leaderboard.

![image](https://user-images.githubusercontent.com/107088092/172747957-3c029e34-d489-4427-b7b2-c886f02e8a99.png)
![image](https://user-images.githubusercontent.com/107088092/172748013-cc73ce27-7891-4160-b4d1-89b7129d65d7.png)

Test case 9: When click CONTINUE FIGHTING on the learderborad, the game should continue to be played
Step: 1. When click CONTINUE FIGHTING on the learderborad
         2. When start to play the game and answer the 1st story chapter.
         3. Then click CONTINUE button.
Expected result: The game should continue.
Actual result: The game jump out to the leaderborad.
![image](https://user-images.githubusercontent.com/107088092/172748633-08077a14-a964-493a-8486-1b58ce513a0b.png)
![image](https://user-images.githubusercontent.com/107088092/172748476-ba01aab7-af98-4421-92e5-6e0215cb4c44.png)
![image](https://user-images.githubusercontent.com/107088092/172748662-e1d700ce-05ab-4988-a4fe-84b73772ba99.png)

Test case 10: When click BACKWARD and FORWARD buttons on the browser, the game shouldn't login.
Step: 1. When click BACKWARD button on the browser to get the login page.
         2. Then click FORWARD button on the browser to go back to the game page.
Expected result: The game shouldn't login.
Actual result: User login successfully. 
![image](https://user-images.githubusercontent.com/107088092/172749952-10b5acad-75f6-46ef-b646-8294380311d2.png)
![image](https://user-images.githubusercontent.com/107088092/172749979-400d11f6-2c61-41bd-8a14-b56a79b24900.png)
![image](https://user-images.githubusercontent.com/107088092/172749952-10b5acad-75f6-46ef-b646-8294380311d2.png)

Test case 11: When give the wrong answer to the 1st chapter, the score should be cleaned.
Step: 1. Given the authorized key, the score is 400, user name: aaaaa, password: 00000.
         2. When give the wrong answer to the 1st chapter.
         3. Then login again.
Expected result: The score should be 0.
Actual result: The score is still 400.

![image](https://user-images.githubusercontent.com/107088092/172750740-b3c0e971-7171-4c50-acef-b80f4dacdc06.png)
![image](https://user-images.githubusercontent.com/107088092/172750776-7f6892ed-77b1-4c76-b7a1-60bf222a8985.png)
![image](https://user-images.githubusercontent.com/107088092/172750810-1dd5abb3-ef27-45a3-bd04-c11b261044ef.png)

**Comment by ale-sanchez-g** [comment]
split in to different defect please
